-- MySQL Script generated by MySQL Workbench
-- Tue Aug  4 15:31:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`produs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produs` (
  `idProdus` INT NOT NULL AUTO_INCREMENT,
  `NumeProdus` VARCHAR(45) NOT NULL,
  `Pret` INT NOT NULL,
  `Image` VARCHAR(45) NULL,
  `ImagePath` VARCHAR(45) NULL,
  PRIMARY KEY (`idProdus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilizator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilizator` (
  `idUtilizator` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idUtilizator`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`history_delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`history_delivery` (
  `idhistory_delivery` INT NOT NULL AUTO_INCREMENT,
  `nume` VARCHAR(45) NOT NULL,
  `prenume` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `pret_total` INT NOT NULL,
  `delivery_list` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`idhistory_delivery`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
