<?php
define("SITE_TITLE","Manager");
define("LOGIN_OK",0);
define("USER_NOT_FOUND",1);
define("PASSWORD_WRONG",2);
define("PASSWORD_NOT_MATCH",3);
define("NEW_USER_OK",4);
define("MAIL_ALREADY_USED",5);
define("MAIL_NOT_FOUND",6);
define("NEW_PASS_EMAIL",7);
define("IS_USER",2);
define("IS_ADMIN",1);
define("BAD",10);
define("GOOD",11);
// Categoriile produselor
define("Горячие Напитки","bauturi calde");
define("Б/А напитки:Холодный Коффе","cafea rece");
define("Б/А напитки:Вода","apa");
define("Б/А напитки:Сок","sucuri");
define("Б/А напитки:Энергетик","energizante");
define("Алкоол. напитки:Вино","vin");
define("Алкоол. напитки:Коньяк","coniac");
define("Алкоол. напитки:Водка","vodka");
define("Алкоол. напитки:Виски","wiski");
define("Алкоол. напитки:Пиво","bere");
define("Продукты:Снэки","Snack-uri");
define("Продукты:Закуска к пиву","Zakuska la bere");
define("Продукты:Орешки","arahide");
define("Продукты:Сладости","dulciuri");
define("Сигареты","tigari");